[package]
name = "next-rs-land"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
next-rs = "0.0.5"
yew = "0.21.0"
yew-router = "0.18.0"
yew-scroll = "0.1.0"
